# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-FileCopyrightText: Netresearch DTT GmbH

ARG BASE_IMAGE
FROM $BASE_IMAGE

# Copy landing page to webroot
COPY landing-index.html /var/www/html/index.html
