services:
  web:
    environment:
      - EXTENSION_KEY=nr_mcp_agent
      - PACKAGE_NAME=netresearch/nr-mcp-agent
      - NR_MCP_AGENT_LLM_TASK_UID
      - TYPO3_DB_DRIVER=mysqli
      - TYPO3_DB_HOST=db
      - TYPO3_DB_PORT=3306
      - TYPO3_DB_DBNAME=db_v14
      - TYPO3_DB_USERNAME=root
      - TYPO3_DB_PASSWORD=root
      - TYPO3_SETUP_ADMIN_EMAIL=admin@example.com
      - TYPO3_SETUP_ADMIN_USERNAME=admin
      - TYPO3_SETUP_ADMIN_PASSWORD=Joh316!!
    volumes:
      - ../:/var/www/nr_mcp_agent:cached
      - v13-data:/var/www/html/v13
      - v14-data:/var/www/html/v14
volumes:
  v13-data:
  v14-data:
